server:
  port: 8000
  servlet:
    context-path: /test
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: party-building
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB